# Generated by Django 5.2.10 on 2026-01-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emoji', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PotionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('min_ingredients', models.IntegerField(default=1)),
                ('max_ingredients', models.IntegerField(default=5)),
            ],
        ),
    ]
