# Generated by Django 5.2.10 on 2026-01-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='color',
            field=models.CharField(default='#ffb3c6', max_length=7),
        ),
    ]
