# Generated by Django 5.2.10 on 2026-01-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potion', '0002_ingredient_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='color',
            field=models.CharField(default='#fef0ff', max_length=7),
        ),
        migrations.AlterField(
            model_name='potionresult',
            name='max_ingredients',
            field=models.IntegerField(default=3),
        ),
    ]
