# Generated by Django 5.2.10 on 2026-01-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potion', '0003_alter_ingredient_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potionresult',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='potion.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='color',
            field=models.CharField(default='#ffc2be', max_length=7),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='emoji',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='potionresult',
            name='max_ingredients',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='potionresult',
            name='min_ingredients',
            field=models.IntegerField(default=3),
        ),
    ]
