# Generated by Django 5.2.10 on 2026-01-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potion', '0004_potionresult_ingredients_alter_ingredient_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='color',
        ),
        migrations.RemoveField(
            model_name='potionresult',
            name='max_ingredients',
        ),
        migrations.RemoveField(
            model_name='potionresult',
            name='min_ingredients',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
