# Generated by Django 5.2.10 on 2026-01-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potion', '0005_remove_ingredient_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potionresult',
            old_name='description',
            new_name='love_letter',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='emoji',
        ),
        migrations.AlterField(
            model_name='potionresult',
            name='ingredients',
            field=models.ManyToManyField(to='potion.ingredient'),
        ),
    ]
